services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes: 
      - mongodbdata:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

  seq:
    image: datalust/seq
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 80:80
    volumes:
      - seqdata:/data

  catalogservice:
    image: ${DOCKER_REGISTRY-}catalogservice
    build:
      context: .
      dockerfile: Services/CatalogService/Dockerfile
    depends_on:
      - mongo
      - rabbitmq

  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: .
      dockerfile: Services/IdentityService/Dockerfile
    depends_on:
      - mongo
      - rabbitmq

  inventoryservice:
    image: ${DOCKER_REGISTRY-}inventoryservice
    build:
      context: .
      dockerfile: Services/InventoryService/Dockerfile
    depends_on:
      - mongo
      - rabbitmq

  tradingservice:
    image: ${DOCKER_REGISTRY-}tradingservice
    build:
      context: .
      dockerfile: Services/TradingService/Dockerfile
    depends_on:
      - mongo
      - rabbitmq

volumes: 
  mongodbdata:
  rabbitmqdata:
  seqdata:
